# For full config options, check the docs: docs.serverless.com

service: oidc-provider2 # Avoid overwriting oidc-provider (v1) service that may already be around.

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 15 # Avoid cold start timeouts.
  region: eu-central-1 # Frankfurt
  stage: ${opt:stage}

functions:
  main:
    handler: src/index.handler

    events:
      - http: ANY {proxy+}

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies